### ISSUE TITLE
Show current context and allow to switch with kpoof

### ISSUE THREAD

**Issue by doerler** [farmotive/kpoof#16]
Hi,

nice project - works even on Windows 10 Using Windows-Subsystem Linux with Ubuntu from Windows store :)

When working with different clusters (i.e. context) it would be really helpful if kpoof would show the current context (`kubectl config get current-context`) and it would be nice beeing able event to switch context (`kubectl config view -o jsonpath='{.contexts[*].name}'`).

Best regards and thanks for the great work
Andreas

**Comment by lypht** [comment]
We predominantly leverage [kubens and kubectx](https://github.com/ahmetb/kubectx) in conjunction with kpoof.  I'll take a look at adding a notifier for current context in the prompt dialog this weekend.  Thanks for the kind words!
