### ISSUE TITLE
Multiple containers in a single pod concatenate the remote port

### ISSUE THREAD

**Issue by lypht** [farmotive/kpoof#4]
Given container `foo` with `PORT: 8080/TCP` and container `bar` with `PORT: 11211/TCP` `kpoof` will show the final prompt as `Note: *nix ports below 1000 are denied, i.e., use '8080' if the pod is exposing 80 or 443. Local port number? (defaults to 808011211):`

Expected result: default to 8080

**Comment by scottrigby** [comment]
Had a great working session. I want to jot down these fun resources for jsonpath:
- light intro: https://kubernetes.io/docs/user-guide/jsonpath/
- docs: http://goessner.net/articles/JsonPath/index.html#e2
- fun little tool (also a little annoying but useful for quick tests): http://jsonpath.com/

**Comment by lypht** [comment]
Will be resolved when https://github.com/farmotive/kpoof/pull/5 is merged.
