### ISSUE TITLE
Add kpoof tests file

### ISSUE THREAD

**Issue by scottrigby** [farmotive/kpoof#8]
Tests file should include:
- [ ] A connected cluster
- [ ] A function for minimal Deployment and Service creation (labeled for easy cleanup)
- [ ] Test functions for all known use cases (multi-container pods, ports above and below certain ranges, etc)
- [ ] A cleanup function

**Comment by lypht** [comment]
Addressing this currently:  From the kubernetes #helm-dev conversation:
1. create test cluster
1. create helm deployments 
1. iterate through n parallel processes (can't be done in one shell) 
1.capture the kubelet memory trend
1. store this data in a useful manner
1. delete the ephemeral cluster
